ALTER TABLE "Proposal" ADD COLUMN "progressPercent" INTEGER NOT NULL DEFAULT 0 CHECK ("progressPercent" BETWEEN 0 AND 100);
ALTER TABLE "Proposal" ADD COLUMN "progressComment" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Proposal" ADD COLUMN "submittedAt" DATETIME;
ALTER TABLE "Proposal" ADD COLUMN "confirmedByBusiness" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Proposal" ADD COLUMN "confirmedPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Proposal" ADD COLUMN "awardedPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Proposal" ADD COLUMN "progressRevision" INTEGER NOT NULL DEFAULT 0;
